services:
  adguardhome:
    image: adguard/adguardhome:v0.107.69
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - "./conf:/opt/adguardhome/conf"
      - "./data:/opt/adguardhome/work/data"
      - "./ssl:/opt/adguardhome/ssl"
    ports:
      - "8080:8080/tcp"
      - "8443:443/tcp"
      - "3000:3000/tcp"
